title: Volker Dorna

collections_dir: ./pages

theme: minima

collections: 
  books:
      output: true
  ada:
      output: true
  duck:
      output: true

sass:
  sass_dir: _sass
  style: compressed 

kramdown:
  enable_coderay: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"