title: Volker Dorna

collections_dir: ./pages

layouts_dir: /_layouts
collections: 
  books:
      output: true
  ada:
      output: true
  duck:
      output: true

sass:
  sass_dir: _sass
  style: compressed 


kramdown:
  enable_coderay: true
